// AUTO-GENERATED by scripts/gen-algs.mjs — every algorithm verified with the
// cubing.js kpuzzle engine. Do not edit by hand; edit the generator and rerun.

export interface PllCase {
  name: string;
  alg: string;
  description: string;
}

export interface OllCase {
  name: string;
  alg: string;
  /** Edge-flip shape group: Cross (edges done), L-shape, Line, Dot. */
  shape: "Cross" | "L-shape" | "Line" | "Dot";
}

export const PLL_CASES: PllCase[] = [
  {
    "name": "Aa",
    "alg": "x R' U R' D2 R U' R' D2 R2 x'",
    "description": "Three corners cycle; edges rest."
  },
  {
    "name": "Ab",
    "alg": "x R2 D2 R U R' D2 R U' R x'",
    "description": "Mirror of Aa — corners cycle the other way."
  },
  {
    "name": "E",
    "alg": "x' R U' R' D R U R' D' R U R' D R U' R' D' x",
    "description": "All four corners trade left-to-right; edges rest."
  },
  {
    "name": "F",
    "alg": "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R",
    "description": "One edge pair and one corner pair swap across."
  },
  {
    "name": "Ga",
    "alg": "R2 U R' U R' U' R U' R2 U' D R' U R D' U",
    "description": "Corners and edges both cycle — the G family."
  },
  {
    "name": "Gb",
    "alg": "R' U' R U D' R2 U R' U R U' R U' R2 D U",
    "description": "G family."
  },
  {
    "name": "Gc",
    "alg": "R2 U' R U' R U R' U R2 U D' R U' R' D U",
    "description": "G family."
  },
  {
    "name": "Gd",
    "alg": "R U R' U' D R2 U' R U' R' U R' U R2 D' U",
    "description": "G family."
  },
  {
    "name": "H",
    "alg": "M2 U M2 U2 M2 U M2",
    "description": "Both pairs of opposite edges swap."
  },
  {
    "name": "Ja",
    "alg": "x R2 F R F' R U2 r' U r U2 x'",
    "description": "A corner pair and an edge pair swap, side by side."
  },
  {
    "name": "Jb",
    "alg": "R U R' F' R U R' U' R' F R2 U' R' U'",
    "description": "Mirror of Ja."
  },
  {
    "name": "Na",
    "alg": "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
    "description": "Diagonal corner swap + opposite edge swap."
  },
  {
    "name": "Nb",
    "alg": "R' U R U' R' F' U' F R U R' F R' F' R U' R",
    "description": "Mirror of Na."
  },
  {
    "name": "Ra",
    "alg": "R U' R' U' R U R D R' U' R D' R' U2 R' U'",
    "description": "Corner pair + edge pair swap."
  },
  {
    "name": "Rb",
    "alg": "R2 F R U R U' R' F' R U2 R' U2 R U",
    "description": "Mirror of Ra."
  },
  {
    "name": "T",
    "alg": "R U R' U' R' F R2 U' R' U' R U R' F'",
    "description": "Right corners swap + left-right edges swap."
  },
  {
    "name": "Ua",
    "alg": "R U' R U R U R U' R' U' R2",
    "description": "Three edges cycle; corners rest."
  },
  {
    "name": "Ub",
    "alg": "R2 U R U R' U' R' U' R' U R'",
    "description": "Three edges cycle the other way."
  },
  {
    "name": "V",
    "alg": "R' U R' U' y R' F' R2 U' R' U R' F R F y'",
    "description": "Diagonal corner swap + adjacent edge swap."
  },
  {
    "name": "Y",
    "alg": "F R U' R' U' R U R' F' R U R' U' R' F R F'",
    "description": "Diagonal corner swap + adjacent edge swap."
  },
  {
    "name": "Z",
    "alg": "M' U M2 U M2 U M' U2 M2 U'",
    "description": "Both pairs of neighboring edges swap."
  }
];

export const OLL_CASES: OllCase[] = [
  {
    "name": "Antisune",
    "alg": "R U2 R' U' R U' R'",
    "shape": "Cross"
  },
  {
    "name": "Bowtie",
    "alg": "F' r U R' U' r' F R",
    "shape": "Cross"
  },
  {
    "name": "H (double Sune)",
    "alg": "R U R' U R U' R' U R U2 R'",
    "shape": "Cross"
  },
  {
    "name": "Headlights",
    "alg": "R2 D R' U2 R D' R' U2 R'",
    "shape": "Cross"
  },
  {
    "name": "Pi",
    "alg": "R U2 R2 U' R2 U' R2 U2 R",
    "shape": "Cross"
  },
  {
    "name": "Sune",
    "alg": "R U R' U R U2 R'",
    "shape": "Cross"
  },
  {
    "name": "T (chameleon)",
    "alg": "r U R' U' r' F R F'",
    "shape": "Cross"
  },
  {
    "name": "Cross-L",
    "alg": "F U R U' R' F'",
    "shape": "L-shape"
  },
  {
    "name": "Fish (kite)",
    "alg": "R U R' U' R' F R2 U R' U' F'",
    "shape": "L-shape"
  },
  {
    "name": "L-shape 1",
    "alg": "F U R U' R' F' U' R2 D R' U2 R D' R' U2 R'",
    "shape": "L-shape"
  },
  {
    "name": "L-shape 10",
    "alg": "F U R U' R' F' R U2 R' U' R U' R'",
    "shape": "L-shape"
  },
  {
    "name": "L-shape 12",
    "alg": "F U R U' R' F' U r U R' U' r' F R F'",
    "shape": "L-shape"
  },
  {
    "name": "L-shape 15",
    "alg": "F U R U' R' F' U R U2 R' U' R U' R'",
    "shape": "L-shape"
  },
  {
    "name": "L-shape 16",
    "alg": "F U R U' R' F' R U R' U R U' R' U R U2 R'",
    "shape": "L-shape"
  },
  {
    "name": "L-shape 17",
    "alg": "F U R U' R' F' U2 R U2 R2 U' R2 U' R2 U2 R",
    "shape": "L-shape"
  },
  {
    "name": "L-shape 18",
    "alg": "F U R U' R' F' U R2 D R' U2 R D' R' U2 R'",
    "shape": "L-shape"
  },
  {
    "name": "L-shape 2",
    "alg": "F U R U' R' F' r U R' U' r' F R F'",
    "shape": "L-shape"
  },
  {
    "name": "L-shape 20",
    "alg": "F U R U' R' F' U2 R U R' U R U2 R'",
    "shape": "L-shape"
  },
  {
    "name": "L-shape 22",
    "alg": "F U R U' R' F' R U2 R2 U' R2 U' R2 U2 R",
    "shape": "L-shape"
  },
  {
    "name": "L-shape 23",
    "alg": "F U R U' R' F' U R U R' U R U' R' U R U2 R'",
    "shape": "L-shape"
  },
  {
    "name": "L-shape 24",
    "alg": "F U R U' R' F' U2 r U R' U' r' F R F'",
    "shape": "L-shape"
  },
  {
    "name": "L-shape 25",
    "alg": "F U R U' R' F' U R U2 R2 U' R2 U' R2 U2 R",
    "shape": "L-shape"
  },
  {
    "name": "L-shape 26",
    "alg": "F U R U' R' F' R U R' U R U2 R'",
    "shape": "L-shape"
  },
  {
    "name": "L-shape 27",
    "alg": "F U R U' R' F' U' R U R' U R U2 R'",
    "shape": "L-shape"
  },
  {
    "name": "L-shape 4",
    "alg": "F U R U' R' F' U' R U2 R' U' R U' R'",
    "shape": "L-shape"
  },
  {
    "name": "L-shape 5",
    "alg": "F U R U' R' F' U2 R2 D R' U2 R D' R' U2 R'",
    "shape": "L-shape"
  },
  {
    "name": "L-shape 6",
    "alg": "F U R U' R' F' U' F' r U R' U' r' F R",
    "shape": "L-shape"
  },
  {
    "name": "L-shape 8",
    "alg": "F U R U' R' F' U R U R' U R U2 R'",
    "shape": "L-shape"
  },
  {
    "name": "P (couch)",
    "alg": "R' U' F U R U' R' F' R",
    "shape": "L-shape"
  },
  {
    "name": "Small lightning",
    "alg": "r U R' U R U2 r'",
    "shape": "L-shape"
  },
  {
    "name": "Small lightning 2",
    "alg": "r' U' R U' R' U2 r",
    "shape": "L-shape"
  },
  {
    "name": "Square-left",
    "alg": "r' U2 R U R' U r",
    "shape": "L-shape"
  },
  {
    "name": "Square-right",
    "alg": "r U2 R' U' R U' r'",
    "shape": "L-shape"
  },
  {
    "name": "W",
    "alg": "R U R' U R U' R' U' R' F R F'",
    "shape": "L-shape"
  },
  {
    "name": "C-shape",
    "alg": "R U R2 U' R' F R U R U' F'",
    "shape": "Line"
  },
  {
    "name": "Cross-line",
    "alg": "F R U R' U' F'",
    "shape": "Line"
  },
  {
    "name": "Knight move",
    "alg": "F U R U' R2 F' R U R U' R'",
    "shape": "Line"
  },
  {
    "name": "Line 1",
    "alg": "F R U R' U' F' U R2 D R' U2 R D' R' U2 R'",
    "shape": "Line"
  },
  {
    "name": "Line 10",
    "alg": "F R U R' U' F' R U R' U R U2 R'",
    "shape": "Line"
  },
  {
    "name": "Line 11",
    "alg": "F R U R' U' F' U2 R U R' U R U2 R'",
    "shape": "Line"
  },
  {
    "name": "Line 12",
    "alg": "F R U R' U' F' R U2 R2 U' R2 U' R2 U2 R",
    "shape": "Line"
  },
  {
    "name": "Line 13",
    "alg": "F R U R' U' F' U R U R' U R U' R' U R U2 R'",
    "shape": "Line"
  },
  {
    "name": "Line 14",
    "alg": "F R U R' U' F' U R U R' U R U2 R'",
    "shape": "Line"
  },
  {
    "name": "Line 15",
    "alg": "F R U R' U' F' r U R' U' r' F R F'",
    "shape": "Line"
  },
  {
    "name": "Line 4",
    "alg": "F R U R' U' F' U R U2 R' U' R U' R'",
    "shape": "Line"
  },
  {
    "name": "Line 5",
    "alg": "F R U R' U' F' R U2 R' U' R U' R'",
    "shape": "Line"
  },
  {
    "name": "Line 7",
    "alg": "F R U R' U' F' U2 R U2 R' U' R U' R'",
    "shape": "Line"
  },
  {
    "name": "Line 9",
    "alg": "F R U R' U' F' F' r U R' U' r' F R",
    "shape": "Line"
  },
  {
    "name": "T-shape",
    "alg": "R U R' U' R' F R F'",
    "shape": "Line"
  },
  {
    "name": "Dot",
    "alg": "R U2 R2 F R F' U2 R' F R F'",
    "shape": "Dot"
  },
  {
    "name": "Dot 1",
    "alg": "F R U R' U' F' U2 F R U R' U' F' F R U R' U' F' U R2 D R' U2 R D' R' U2 R'",
    "shape": "Dot"
  },
  {
    "name": "Dot 2",
    "alg": "F R U R' U' F' U2 F R U R' U' F' F R U R' U' F' R U R' U R U' R' U R U2 R'",
    "shape": "Dot"
  },
  {
    "name": "Dot 3",
    "alg": "F R U R' U' F' U2 F R U R' U' F' F R U R' U' F'",
    "shape": "Dot"
  },
  {
    "name": "Dot 4",
    "alg": "F R U R' U' F' U2 F R U R' U' F' F R U R' U' F' R U R' U R U2 R'",
    "shape": "Dot"
  },
  {
    "name": "Dot 5",
    "alg": "F R U R' U' F' U2 F R U R' U' F' F R U R' U' F' R U2 R' U' R U' R'",
    "shape": "Dot"
  },
  {
    "name": "Dot 6",
    "alg": "F R U R' U' F' U2 F R U R' U' F' F R U R' U' F' U R U R' U R U2 R'",
    "shape": "Dot"
  },
  {
    "name": "Dot 7",
    "alg": "F R U R' U' F' U2 F R U R' U' F' F R U R' U' F' U R U R' U R U' R' U R U2 R'",
    "shape": "Dot"
  }
];
